# Generated by Django 5.0.6 on 2024-06-22 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userbankaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='country',
        ),
    ]
