# Generated by Django 5.0.6 on 2024-06-24 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_purchase_book_alter_purchase_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
