# Generated by Django 5.0.6 on 2024-06-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
        ('catagories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='catagories',
        ),
        migrations.AddField(
            model_name='book',
            name='catagories',
            field=models.ManyToManyField(to='catagories.catagories'),
        ),
    ]
