# Generated by Django 5.0.6 on 2024-06-21 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_review_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
