# Generated by Django 5.0.6 on 2024-06-22 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_delete_purchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
