# Generated by Django 5.0.6 on 2024-06-24 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
